version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - sed -i -e 's/\r$//' ./cloudformation/buildspec_postbuild.sh
      - sed -i -e 's/\r$//' ./bin/deploy.sh
      - chmod +x ./cloudformation/buildspec_postbuild.sh
      - chmod +x ./bin/deploy.sh
  build:
    commands:
      - npm i
      - npm run tsc
      - cp -R ./node_modules ./dist
  post_build:
    commands:
      - ./cloudformation/buildspec_postbuild.sh