AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  AwsNamespace:
    Type: String
    Description: Used to generate namespaced AWS resources
Resources:
  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub cicd-pipeline-basic-function
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: ../dist
      MemorySize: 192
      Timeout: 30
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
                - "ssm:DescribeParameters"
                - "ssm:PutParameter"
                - "ssm:GetParameterHistory"
                - "ssm:GetParametersByPath"
                - "ssm:GetParameters"
                - "ssm:GetParameter"
              Resource: '*'
